# -*- coding: utf-8 -*-
"""cifar10_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qa-9hJP3BdiNy0OMsbVmFFBpMJlLyHyT
"""

# Importing all necessary modules
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# Loading CIFAR-10 with data augmentation
transform_train= transforms.Compose([transforms.RandomHorizontalFlip(),
                                     transforms.ToTensor(), transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))])

# Displaying 8 images with class label
fig, axes= plt.subplots(1,8,figsize=(16,2))
train_data= torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform= transform_train)
train_loader= torch.utils.data.DataLoader(train_data, batch_size=8, shuffle= True)
images, labels =next(iter(train_loader))
classes = ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
for i, image in enumerate(images):
  if i==8:
    break
  axes[i].imshow(np.transpose(image.numpy(), (1,2,0)))
  axes[i].set_title(classes[labels[i]])

# Creating the CNN class
class CNN(nn.Module):
 def __init__(self):
   super().__init__()
   self.conv1= nn.Conv2d(3,32, kernel_size=3, padding=1)
   self.conv2= nn.Conv2d(32, 64, kernel_size=3, padding=1)
   self.pool= nn.MaxPool2d(2,2)
   self.fc1=nn.Linear(64*8*8,512)
   self.fc2=nn.Linear(512,10)
   self.relu= nn.ReLU()
   self.drop= nn.Dropout(0.3)
 def forward(self,x):
  x=self.pool(self.relu(self.conv1(x)))
  x=self.pool(self.relu(self.conv2(x)))
  x=x.view(x.size(0), -1)
  x=self.drop(self.relu(self.fc1(x)))
  return self.fc2(x)

model = CNN()
x= torch.rand(32,3,32,32)
print(model(x).shape)